### ISSUE TITLE
Compatible with MySQL Database? 

### ISSUE THREAD

**Issue by sanjaypradeep** [sajib1066/django-ecommerce#5]
`interested to use this - django.db.backends.mysql`

**Comment by sajib1066** [comment]
ok, I will set up the MySQL database for this project.

**Comment by sanjaypradeep** [comment]
I did, it's working with MySQL.

Means, I could able to do `migrate`

**Comment by sajib1066** [comment]
can you please send me your error message. i checked it, all is ok.
